Indexed covid zones in scraper to enable faceted search on modules page
nusmodifications/nusmods pull request #2784
Opened 2020-07-26 02:47 UTC by ZhangYiJiang

## Context

## Implementation

## Other Information

2020-07-26 18:56 UTC, ZhangYiJiang commented on scrapers/nus-v2/src/utils/data.test.ts
> -
Dead code which somehow never got removed, lol

2020-07-26 18:58 UTC, ZhangYiJiang commented on scrapers/nus-v2/tsconfig.json
> +    "target": "es2018",
This was a misconfiguration from a previous PR. The `target` is the output's language support level, which should not be `es2020` since Node 12 doesn't support optional chaining. The `lib` should be, because we want `Array#flat` and Node 12 does support that (should probably check if other APIs are also support - we don't use Babel for the scraper, and there might be ES2020 APIs not supported by Node 12 yet)

2020-10-18 02:53 UTC, taneliang approved these changes
Thank you!

2020-10-18 04:48 UTC, taneliang requested changes

2020-10-18 04:48 UTC, taneliang commented on scrapers/nus-v2/src/services/io/elastic.ts
> +        filter: { first_token_limit_filter, thousandizer_filter },
Actually hold on, this errors because they're static settings (putSettings can only update dynamic settings). https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-modules-settings

2020-10-18 04:48 UTC, taneliang commented
I'll fix this. I'm also gonna upgrade us to Elasticsearch 7 since Searchkit has gained support for it.

2020-10-19 04:20 UTC, taneliang approved these changes
Made a few changes:

- Merged master, which now works with ES 7.
- Changed this PR to scrape to a new `modules_v2` ES index as we can't migrate the existing index. More details at [`6c9f598` (#2784)](https://github.com/nusmodifications/nusmods/pull/2784/commits/6c9f598c233baf3309b868679fcb8f9eb426f921).
- Updated website to use the new index.
- Fixed website queries to work with new nested `semesterData`.

@ZhangYiJiang could you take a last look at the changes?

### Test plan

Manually tested scraper:

1. Scraped to `modules` index using scraper on `master`.
1. Checked out this branch and ran `yarn dev all`. A new index was created and populated.

![image](https://user-images.githubusercontent.com/12784593/96400966-bc1b3180-1204-11eb-8006-7476a09a90c7.png)

Manually checked the fixed exam filter:

| Master | This PR|
|-|-|
|![image](https://user-images.githubusercontent.com/12784593/96400694-005a0200-1204-11eb-834b-e6aa3104516a.png)|![image](https://user-images.githubusercontent.com/12784593/96400685-f932f400-1203-11eb-84fd-2bc5ab6b3616.png)|

Not sure why there's 1 more mod without exam now, but the filter looks correct so I don't think anything broke.

### Deployment plan

We'll want to hold off on merging this until we upgrade to ES 7 so that we don't change too many things at once.

As discussed on Telegram:

1. Upgrade NUSMods to ES 7 with the current code on master.
1. Merge this PR.
1. Deploy and run new scraper.
1. Check Kibana to ensure new data is populated correctly on the production ES server.
1. Deploy new frontend.
1. Delete `modules` index on production ES server.

2020-10-19 04:22 UTC, taneliang commented
Also checked that `semesterData.covidZones` exists in the ES index.

![image](https://user-images.githubusercontent.com/12784593/96401364-a0fcf180-1205-11eb-8aea-a99fda13029b.png)

2020-10-19 17:21 UTC, ZhangYiJiang commented
I think it looks good, but again you have more experience with ES than me, and I don't have it set up locally that I can test this

2020-10-19 20:38 UTC, ZhangYiJiang commented
Also we should follow up with the last PR to actually add a facet filter to the module page

2020-10-20 02:27 UTC, taneliang commented
Great! Let's merge and deploy the scraper now, and we can update the website tonight.

2020-10-20 02:33 UTC, merged