Save e-learning venues as E-Learning in scraper
nusmodifications/nusmods pull request #2823
Opened 2020-08-16 16:36 UTC by chrisgzf

Follow up to: https://github.com/nusmodifications/nusmods/pull/2736

This PR changes the scraper to save lesson venues as "E-Learning" when the API returns a `room` of `E-Learn_*` for lessons.

To see current shaped of our scraped data: https://nusmods.com/api/v2/2020-2021/modules/CS1010.json

@ZhangYiJiang does this look right to you? Also would need some help to test this, if possible.

2020-08-16 16:41 UTC, chrisgzf commented on scrapers/nus-v2/tsconfig.json
> +    "lib": ["dom", "es2020"],
@ZhangYiJiang saw your comment about the `target` here https://github.com/nusmodifications/nusmods/pull/2784#discussion_r460561430, I also added `"dom"` to `lib` because the `URL()` calls were throwing errors in my tests: `Cannot find name 'URL'. Did you mean 'url'?` Not sure if you've encountered this too but adding `"dom"` fixed this for me.

2020-08-16 19:40 UTC, ZhangYiJiang commented on scrapers/nus-v2/tsconfig.json
> +    "lib": ["dom", "es2020"],
That's probably not correct - this code will only be run in Node.js, and while `dom` lib will add URL as a global like in Node 10/12, it will also add a bunch of other globals like `document` and `navigator` which are not valid. The correct way to fix this is to use the `@types/node` typing, but it doesn't add globals unless it is imported at least once, so in the end it's probably best to just import `URL` explicitly `import { URL } from 'url';`

2020-08-16 19:48 UTC, ZhangYiJiang commented on scrapers/nus-v2/src/tasks/GetSemesterTimetable.test.ts
> +      }),
```suggestion
      CS4238Timetable.map((lesson) => ({ ...lesson, room: 'E-Learn_C' }));
```

2020-08-16 19:48 UTC, ZhangYiJiang commented on scrapers/nus-v2/src/tasks/GetSemesterTimetable.ts
> +    room: providedRoom,
This avoids the `|| ''` and `?.` below 

```suggestion
    room: providedRoom = '',
```

2020-11-30 06:33 UTC, taneliang requested changes
Oops, one semester has passed. As [zoning restrictions will be lifted on 6 Dec](https://emergency.nus.edu.sg/circulars/wp-content/uploads/2020/10/2020-1031-OSHE-COVID-19-Circular-28-08.14.pdf), I'm not sure how these venue names will change. Let's hold off work on this PR until we have more information.

2026-05-23 04:21 UTC, ravern commented
Hey, we're doing some clean ups over the summer. Closing this for now because both the issue and the PR are stale. Feel free to re-open this if you think otherwise!

2026-05-23 04:21 UTC, closed without merging