Add support for year-long modules to module planner
nusmodifications/nusmods pull request #2913
Opened 2020-10-17 16:40 UTC by jeffsieu

## Context
Resolves #1912

## Implementation

### Before add

![image](https://user-images.githubusercontent.com/8487294/96348312-6ba7b500-10da-11eb-9ef9-b478bf88fe8d.png)

### After add

![image](https://user-images.githubusercontent.com/8487294/96347953-e4f1d880-10d7-11eb-889a-3e392a3c98cc.png)

Represents year long modules as modules in semester 0. Year-long modules are moved to the list whenever added from Semester 1 or 2.

### Misc
- "+ Add modules" section removed to avoid clutter. Also avoids the case where non year-long modules are added from the year-long "add modules" section
- Adds `type` attribute to `Droppable` targets to disallow dragging of modules to the lists of the wrong module type.
- Some test cases are modified to due to the extra "semester".

## Other Information

Currently, the year long section is hidden until at least one module is in the year long list. Dragging over another year should bring up a placeholder as a drag target

2020-10-20 18:21 UTC, ZhangYiJiang requested changes
This looks great! I do think we might want to change the data structure from the scraper to allow us to do this more naturally. Let me know if you need help with that

2020-10-20 18:21 UTC, ZhangYiJiang commented on website/src/utils/planner.ts
> +export const YEAR_LONG_SEMESTER: Semester = 0;
This is problematic - 0 comes before all the other semesters, so a year long module would fulfill prerequisites for other modules taken in the same year, when the opposite should be true. In general we might want to re-think this hack of using specially coded semester values - it might be better to type this instead 

``` ts 
type Semester = 1 | 2 | 3 | 4;
type PlannerSemester = Semester | 'yearLong' | 'exemption' | 'planToTake';
``` 

but this will have other impact with regards to sorting

2020-10-20 18:21 UTC, ZhangYiJiang commented on website/src/views/planner/PlannerContainer/PlannerContainer.tsx
> +              this.props.moveYearLongModule(year, semester, moduleCode);
If I understand the UI correctly, the way to add a year long module is to add it to either semester, then this code will move it to the year long section. 

That's a bit awkward - it means for at least one render the module will be in the wrong section, and there is also no real guarantee that the module will be added to the correct location, eg. if the module failed to load, which would leave the data in an inconsistent state since the module is still in the wrong location in the planner. 

We might want to instead think of adding `yearLong` flag to ModuleCondensed - we need this info for use in module search anyway, so it makes sense. This does require a change to the scraper though.

2020-10-20 18:59 UTC, jeffsieu commented on website/src/views/planner/PlannerYear.tsx
> +            [styles.hideSemester]:
I tried that at first, but that causes the element to disappear right as the module is dropped on it. Then it will throw an error as the drop target is no longer there to receive it.

2020-10-20 19:44 UTC, jeffsieu commented on website/src/utils/modules.ts
> +export function isYearLongModule(module: Module): boolean {
I suppose that could be done, but I was thinking of hiding it under a layer of abstraction.

2020-10-20 19:52 UTC, jeffsieu commented on website/src/utils/planner.ts
> +export const SEMESTER_LONG = 'SEMESTER';
This is used to set the type of PlannerModule as part of its id , so that the drop areas can only accept the currently dragged element if it should accept it (sem 1 shouldn't accept a year-long mod)

2020-12-30 05:14 UTC, jeffsieu commented
@ZhangYiJiang How should I proceed with this PR? I really wish to see these changes be incorporated.

2020-12-30 19:35 UTC, ZhangYiJiang reviewed
Sorry for not coming back to review this. This looks almost ready - just a few things 

- The reducers and actions that are now unused should be removed 
- Semester 0 should not be a valid global semester value, instead we can add something specifically for the planner 
- Drag and drop ID and module type should be strongly typed instead of just being strings

2020-12-30 19:35 UTC, ZhangYiJiang commented on scrapers/nus-v2/src/tasks/CollateModules.ts
> +  yearLong: Boolean(attributes ? attributes.year : false),
`Boolean(undefined) === false` 

```suggestion
  yearLong: Boolean(attributes.year),
```

2020-12-30 19:35 UTC, ZhangYiJiang commented on website/src/utils/planner.ts
> +export const YEAR_LONG_SEMESTER: Semester = 0;
Bump

2020-12-30 19:35 UTC, ZhangYiJiang commented on website/src/views/planner/PlannerYear.tsx
> +            [styles.hideSemester]:
Should add a comment then

2020-12-30 19:35 UTC, ZhangYiJiang commented on website/src/views/planner/PlannerModuleSelect.tsx
> +                      onSelect(modules.find((module) => module.moduleCode === inputValue) ?? null);
This would break existing functionality where this field allows multiple module codes to be entered at once here https://github.com/nusmodifications/nusmods/blob/3e844019534912609e38cb546fa3e2b57f7279f6/website/src/views/planner/AddModule.tsx#L133

The logic for validating module code should be on the parent component, not the child.

`onSelect` did have incorrect typing - `ModuleCode` should just be `string`, sorry about that

2020-12-30 19:35 UTC, ZhangYiJiang commented on website/src/views/planner/PlannerSemester.tsx
> +  draggedModuleType: string | null;
This should be explicitly typed as a union of all valid values. 

``` ts 
type ModuleTypes = 'YEAR_LONG' | 'SEMESTER_LONG'
``` 

It would also make it easier to follow if these are constructed and deconstructed in a type safe manner using functions 

``` ts 
function getDraggableId(moduleCode: ModuleCode, moduleType: ModuleType)

// Alternatively this can also return a tuple
function fromDraggableId(id: string): { moduleCode: ModuleCode, moduleType: ModuleType }
``` 

Also it seems that draggable type can be either `SEMESTER_LONG` or `YEAR_LONG` whereas droppable types are `SEMESTER_LONG`, `YEAR_LONG` and `DEFAULT`, but it's hard to tell what DEFAULT should mean - I think from reading the code it means it accepts all module types, in which case it should probably just be ALL - a comment would be really helpful

2021-01-01 09:35 UTC, jeffsieu commented on website/src/views/planner/PlannerModuleSelect.tsx
> +                      onSelect(modules.find((module) => module.moduleCode === inputValue) ?? null);
Actually, how does the adding multiple module codes part work? Since `onSelect(inputValue)` seems to call this: https://github.com/nusmodifications/nusmods/blob/486cca0eda81a361485ee6e79ba219d67dd72c9e/website/src/views/planner/AddModule.tsx#L60-L69
which seems to add only 1 module

2021-01-03 00:45 UTC, ZhangYiJiang commented on website/src/views/planner/PlannerModuleSelect.tsx
> +                      onSelect(modules.find((module) => module.moduleCode === inputValue) ?? null);
It's in this function https://github.com/nusmodifications/nusmods/blob/4ba9c9bb893715c29c98300dff4b4032c650c62c/website/src/views/planner/PlannerContainer/PlannerContainer.tsx#L93. Again the types are wrong and the name is a bit misleading - moduleCode is matched to search for anything that looks like a module code

2021-01-07 01:43 UTC, jeffsieu commented on website/src/views/planner/PlannerModuleSelect.tsx
> +                      onSelect(modules.find((module) => module.moduleCode === inputValue) ?? null);
@ZhangYiJiang I changed the logic so that the module code extraction is done in `PlannerModuleSelect`, and `PlannerContainer.onAddModule` now only handles a single module at a time. i.e. `AddModuleData`'s type has also been modified. This decision was made because I needed the `yearLong` property of every module. And `PlannerModuleSelect` does have a reference to `modules` from which I can extract ModuleCondensed instances out of.

2021-01-12 03:59 UTC, ZhangYiJiang reviewed
Looking very close! Please revert some of the changes that are outdated, run the linter, and avoid using cast in favor of type guards, and this PR should be good to go

2021-01-12 03:59 UTC, ZhangYiJiang commented on website/src/types/modules.ts
> +export const Semesters: readonly Semester[] = [0, 1, 2, 3, 4];
Please revert this

2021-01-12 03:59 UTC, ZhangYiJiang commented on website/src/selectors/planner.test.ts
> +      [0]: [],
Please revert these changes

2021-01-12 03:59 UTC, ZhangYiJiang commented on website/src/utils/planner.ts
> +export function isSemester(plannerSemester: PlannerModuleSemester | string) {
This makes the function a type guard which means you won't need to cast https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards 

```suggestion
export function isSemester(plannerSemester: PlannerModuleSemester): plannerSemester is Semester { 
```

2021-01-12 03:59 UTC, ZhangYiJiang commented on website/src/selectors/planner.ts
> +  mapNonTimetableModules(state, PLAN_TO_TAKE_YEAR, 'planToTake');
On L205 the code is still iterating over `Semesters` which does not include `yearLong`, so year long modules will never correctly count towards fulfilling prereqs.

2021-01-17 17:43 UTC, jeffsieu commented
@ZhangYiJiang Most issues should be resolved. There's currently still a circular dependency between types/planner.ts and types/reducers.ts.... I'm not sure how to resolve this without shifting the type declarations over from a file to the other.

2023-07-03 06:51 UTC, yangshun commented
Guys, merge this plox

2026-05-23 04:21 UTC, ravern commented
Hey, we're doing some clean ups over the summer. Closing this for now because both the issue and the PR are stale. Feel free to re-open this if you think otherwise!

2026-05-23 04:21 UTC, closed without merging