Refactor to use FC and useMediaQuery [SideMenuComponent]
nusmodifications/nusmods pull request #3042
Opened 2020-12-10 08:22 UTC by BransonNg

## Context
#3032 
Replacing HOC MakeResponsive with hook useMediaQuery

## Implementation
Change of class component to functional component so that we can use the hook.

## Other Information

2020-12-10 08:22 UTC, BransonNg commented
Once this passes, I'll do a separate PR for all the other components using MakeResponsive at one go

2020-12-13 01:27 UTC, ZhangYiJiang requested changes

2020-12-13 01:27 UTC, ZhangYiJiang commented on website/src/views/components/SideMenu.tsx
> +  const { isOpen, toggleMenu, children } = props;
There shouldn't be a need for this - just put these on line 29

2020-12-13 01:27 UTC, ZhangYiJiang commented on website/src/views/components/SideMenu.tsx
> +    disableScrolling(isSideMenuShown);
This should have a cleanup function, otherwise scrolling will never be re-enabled if this component unmounts when the menu is open

2020-12-13 02:27 UTC, BransonNg commented on website/src/views/components/SideMenu.tsx
> +    disableScrolling(isSideMenuShown);
Sure, latest commit addresses both issues! Thank u for the review :)

2020-12-13 03:06 UTC, ZhangYiJiang approved these changes

2020-12-13 08:00 UTC, merged