Add MPE page introduction content
nusmodifications/nusmods pull request #3183
Opened 2021-01-20 11:51 UTC by alissayarmantho

## Context

#3035 

Add MPE page introduction content.

## Implementation

Added content to `website/src/views/mpe/MpeContainer.tsx` and its corresponding styling.

## Other Information

2021-01-20 12:40 UTC, taneliang requested changes

2021-01-20 12:40 UTC, taneliang commented on website/src/views/mpe/MpeContainer.scss
> +}
Hmm the formatting is a bit off. Could you run Prettier on this? You could set up your editor to automatically format on save for convenience

2021-01-20 19:18 UTC, alissayarmantho commented on website/src/views/mpe/MpeContainer.scss
> +}
Alright fixed.

2021-01-21 07:07 UTC, taneliang approved these changes
Nice, thanks :D

2021-01-21 07:08 UTC, merged