Add Toggling of Prerequisites Checks for Planner
nusmodifications/nusmods pull request #3374
Opened 2021-12-22 08:58 UTC by seanlowjk

## Context

Fixes #3369 

## Implementation

Under `PlannerState`, adds a boolean flag `prereqsCheck` to allow the 
toggling of prerequisites check. This ensures that the the numerous warnings 
do not overwhelm the user when planning his or her users. 

## Other Information

https://user-images.githubusercontent.com/42912708/147061651-2d1924f1-29fc-44b9-8cfc-f06075258ff0.mp4

Attached above is the implementation video mock-up done.

2021-12-29 21:27 UTC, chrisgzf requested changes
Very good stuff! Thanks for your work! Some small changes else LGTM!

2021-12-29 21:27 UTC, chrisgzf commented on website/src/views/planner/PlannerSettings.tsx
> +            modules you are taking are enforced.
Hmm.. sounds very scary. Perhaps something like:

"Prerequisite checking for some modules might be inaccurate, giving planner warnings. Toggling this off removes these checks. Please ensure that you manually check that the prerequisites for the modules you would like to take are sufficiently met."
might sound slightly better?

2021-12-29 21:27 UTC, chrisgzf commented on website/src/selectors/planner.ts
> +        prereqConflict(moduleBank.modules, modulesTaken, planner.prereqsCheck),
This is a small nit but I find it slightly weird that the actual checking if prereqs should be checked (damn, what a mouthful) is done inside `prereqConflict`.

I'd prefer to leave `prereqConflict` as-is, where it does its job of checking for the prereqs conflict without having to access the planner's state.

Instead, we decide if we want to actually run the `prereqConflict` function in this selector itself, so that the state is contained within this selector.

Something like:
```
if (planner.prereqsCheck) {
  conflictChecks.push(prereqConflict(...));
}
```

2021-12-29 21:27 UTC, chrisgzf commented on website/src/types/reducers.ts
> +  prereqsCheck: boolean; // To enforce check of prerequisites.
```suggestion
  prereqsCheck: boolean; // To turn checking of prerequisites on/off
```

2021-12-30 02:17 UTC, seanlowjk commented on website/src/views/planner/PlannerSettings.tsx
> +            modules you are taking are enforced.
Ah alright!

2021-12-30 02:18 UTC, seanlowjk commented on website/src/views/planner/PlannerSettings.tsx
> +            program that allows full-time NSmen to read some modules before matriculating.
Welcome! 💯

2021-12-30 02:18 UTC, seanlowjk commented on website/src/selectors/planner.ts
> +        prereqConflict(moduleBank.modules, modulesTaken, planner.prereqsCheck),
ah yes, this is a much better way of handling it instead of modifying the method signature!

Thank you for your suggestion!

2021-12-30 02:19 UTC, seanlowjk commented on website/src/types/reducers.ts
> +  prereqsCheck: boolean; // To enforce check of prerequisites.
👍

2021-12-30 02:49 UTC, seanlowjk commented
Have made the following modifications, thank you! 🙏 @chrisgzf

2021-12-30 22:18 UTC, ZhangYiJiang requested changes
Thanks for doing this! The migration is blocking, the UX improvement is good to have.

2021-12-30 22:18 UTC, ZhangYiJiang commented on website/src/reducers/planner.ts
> +  prereqsCheck: true,
This defaults true for new users, but for users who have already used NUSMods this will be `undefined` which is not allowed under types, and when evaluated as a boolean becomes false. You'll want to set up a migration like this one https://github.com/nusmodifications/nusmods/blob/33df1bcca8898b7997dd2f7e728734edf3caa7ad/website/src/reducers/planner.ts#L161 to set up the initial state correctly for existing users

2021-12-30 22:18 UTC, ZhangYiJiang commented on website/src/views/planner/PlannerSettings.tsx
> +      <section className={styles.toggleSection}>
It might be worth considering allowing this to be toggled off per module instead of globally. This would mean the data is stored as an array of ignored module + year + semester instead to identify which module the user has ignored, and the user can ignore them via either menu item on the card or on the warning itself.

2021-12-30 22:19 UTC, ZhangYiJiang commented on website/src/reducers/planner.ts
> +  prereqsCheck: true,
Alternatively, define the state as `ignorePrereqCheck?: boolean` instead - this will satisfy the typing without having to write a migration. The values need to be reversed of course

2021-12-31 01:37 UTC, seanlowjk commented on website/src/reducers/planner.ts
> +  prereqsCheck: true,
Ah thanks for the catch! Will fix this in due time!

2021-12-31 01:42 UTC, seanlowjk commented on website/src/views/planner/PlannerSettings.tsx
> +      <section className={styles.toggleSection}>
Ah yes, that would definitely be more concise. 
Think it would better to do so, but adjustments will definitely be needed to be made :P

Do you think we can still keep the global toggle or is it best to just have the feature for toggles per module?

2022-01-01 10:38 UTC, seanlowjk commented on website/src/views/planner/PlannerSettings.tsx
> +      <section className={styles.toggleSection}>
Think we can leave this for a future PR which I can work on, as we would need to flesh out the details and implementation details! 

Will this be fine? >< @chrisgzf @ZhangYiJiang

2022-01-01 22:56 UTC, chrisgzf requested changes
Last change from me: Can we rename all `setPrerequisitesCheck` and `SET_PREREQUISITES_CHECK` to `setIgnorePrerequisitesCheck` and `SET_IGNORE_PREREQUISITES_CHECK` instead? So that it's not ambiguous what the boolean values mean.

2022-01-02 02:15 UTC, seanlowjk commented
Changes fixed, thanks for pointing it out! @chrisgzf

2022-01-02 21:30 UTC, chrisgzf commented on website/src/views/planner/PlannerSettings.tsx
> +      <section className={styles.toggleSection}>
Yup! Definitely okay to merge this first to alleviate the problem for now. I feel like a better long term fix might be to make the prerequisite checking more robust. We can do so by writing an algo for the prereq-checking detection that assumes that preclusions of a module (e.g. CS1010 precludes CS1101S) also fulfil the same prereqs fulfilled by the module. I will create an issue for this soon.

2022-01-02 21:32 UTC, chrisgzf commented on website/src/views/planner/PlannerSettings.tsx
> +            modules you are taking are enforced.
Updated the wordings in https://github.com/nusmodifications/nusmods/pull/3374/commits/482cadf31e194f38c316937de47bd51c13096dec

2022-01-02 21:33 UTC, chrisgzf approved these changes
I've updated the wordings for the UI change in https://github.com/nusmodifications/nusmods/pull/3374/commits/482cadf31e194f38c316937de47bd51c13096dec to reflect the boolean negation. Everything looks good now. Thanks for your hard work!

2022-01-02 21:35 UTC, merged