Feat/customize mod
nusmodifications/nusmods pull request #3420
Opened 2023-01-01 09:30 UTC by Zhou-Jiahao-1998

## Context

Part of #3404 

## Implementation

Changed the value of `ModuleLessonConfig` type to `classNo[]`.
This change does not affect anything for its current functionality.
New redux actions will be added to add/remove classes to the array.
This will allow TAs to customise the module.

## Other Information

The current idea is to add an extra button next to the remove and hide button of the module and allow student to add/remove classes as they click.

2023-01-30 03:44 UTC, li-kai reviewed
Hi! Thanks for submitting the PR, the code looks good to me.

Enabling custom removal/addition of lessons is such a powerful utility that we want to make sure users wield it right. That means we have to make it obvious which lessons were added/removed, and also the ability to undo them. The consequence of a someone missing lessons/lectures for a semester is pretty big.

As a team we just couldn't come up with a good solution. Ultimately NUSMods is more of a planner than a calendar, so we've been encouraging users customize their schedule via calendar apps instead.

Despite that, it does seem that demands for such a feature never back down. If you're keen on building it, could you propose how your TA-mode would work? Once the details are ironed out, you'll have the go-ahead.

2023-02-05 07:26 UTC, zhoukerrr commented
@li-kai This is how I plan to do this for now.

UI side:
* A new button with the setting icon will be added next to the delete/hide button for each of the modules at the bottom
* To avoid accidental modification, a pop up window will display a warning 
* If the user chooses to proceed, the timetable will enter the state where all possible slots for that module are now selectable/removable
* At this point, buttons next to the module below will turn into a **DONE** button, this will end the customisation mode
* A special symbol/word (e.g. **TA**) could be placed on **ALL** of the slots for modules to emphasis that the module has been customised

Code side:
* Implement the UI mentioned above
* A new redux state that stores the modules that are customised will be added.
* Upon entering the customisation state, classes will be added/removed from the array done in this PR

Let me know your thoughts on this approach. Feel free to share any ideas/comments that you have. Thank you!

2023-02-11 23:56 UTC, li-kai commented
On the UI, it might be better to collapse all 3 into a dropdown so we have:
    - Hide All
    - Delete All
    - Edit Individually <- this triggers modal

But the rest of the details sound good to me. @chrisgzf do you have bandwidth to review the PRs?

2023-02-19 07:24 UTC, zhoukerrr commented
Hi @li-kai @chrisgzf, may I know if this PR can be merged first is that I can push out my next PR? I am almost done with the changes but I do not want to send in a giant PR that is difficult to review. Thank you!

2023-02-21 06:41 UTC, chrisgzf requested changes
Hi @zhoukerrr, changes look okay to me but one more thing. Could you:
- increment the redux-persist schema version in `timetables.ts:25`
- write a migration in the same `persistConfig` to migrate the users' existing data to the new data shape?

This prevents this change from breaking the user's existing timetable data, which will be very messy.

2023-03-18 12:57 UTC, zhoukerrr commented
@li-kai @chrisgzf Hi! May I know if this PR can be merged?

2023-03-19 12:30 UTC, chrisgzf approved these changes
Some last queries else LGTM

2023-03-19 12:30 UTC, chrisgzf commented on website/src/reducers/timetables.test.ts
> +      version: 2,
should this be `1`?

2023-03-19 12:30 UTC, chrisgzf commented on website/src/reducers/timetables.test.ts
> +  });
Thanks for writing tests for the migration!

2023-03-19 12:30 UTC, chrisgzf commented on website/src/reducers/timetables.test.ts
> +      version: 2,
I think the version incrementing is done by the framework and not your function,  so if thats the case I think we can just leave a comment here so that it isn't confusing to others (or just remove the `_persist` key all together (though I guess that might give you type errors).

2023-03-19 12:49 UTC, zhoukerrr commented on website/src/reducers/timetables.test.ts
> +      version: 2,
@chrisgzf yes. Removing `_persist` here will give type error. This is just for the purpose of testing. I had to keep the value identical here to pass the test because in the unit test here the framework doesn't do the magic for us. I will make a comment next to it to avoid any future confusion.

2023-03-19 13:05 UTC, merged