Change global search dropdown to Link
nusmodifications/nusmods pull request #3468
Opened 2023-07-28 01:24 UTC by jloh02

## Context
Currently, global search results cannot be opened in a new tab. This is due to the implementation using downshift's onChange rather than `<a>` tags or `<Link>`
#3466 

## Implementation
By switching from using the `onChange` listener from downshift to a <Link> tag, we can allow users to open search results in new tabs like a normal `<a>` link. Using `<Link>` mimics the `router.push` behavior where other UI components are not reloaded when the link is clicked normally.

Current context menu only shows back
![Screenshot (67)](https://github.com/nusmodifications/nusmods/assets/36648707/ca58432d-73dd-40d4-abab-75c46eda7be7)

Proposed changes allows opening in new tab
![Screenshot (66)](https://github.com/nusmodifications/nusmods/assets/36648707/087c59bf-93cd-485b-a971-6b7f76a846f3)

## Other Information
- First contribution and first time using React component
- Not sure if using the <Link> tag affected the CSS styles in any other way. Looks visually similar on my end

2023-07-31 03:50 UTC, ZhangYiJiang commented on website/src/views/layout/GlobalSearch.tsx
> -        onChange={this.onChange}
This breaks keyboard navigation. One way to fix this is to keep the original logic and add `onClick={(evt) => evt.preventDefault()}` to the anchors so they still use the same logic when clicked (we also don't need them to be `Link` in that case but that's not a big deal)

2023-08-08 08:52 UTC, jloh02 commented on website/src/views/layout/GlobalSearch.tsx
> -        onChange={this.onChange}
Keyboard navigation fixed in c6d65db9430b0fd79d9c85eef455505e1f799020

2023-08-08 10:01 UTC, zwliew requested changes

2023-08-08 12:26 UTC, jloh02 commented on website/src/views/layout/GlobalSearch.scss
> +@import "~styles/utils/modules-entry";
e7b177a827afcd601c3456498d166e1b9e2c0270

2023-08-08 12:28 UTC, jloh02 commented on website/src/views/layout/GlobalSearch.tsx
> +};
Not sure why but a few weeks back the linter gave me warnings requiring me to put a `default`. Anyways resolved in 2acbd15ba237914a47876e948518b806c3921b7d

2023-08-08 13:26 UTC, zwliew approved these changes

2023-08-08 13:29 UTC, zwliew commented on website/src/views/layout/GlobalSearch.tsx
> +};
It's cases like this when I think the `consistent-return` rule should be disabled, but eh -- this is fine. :)

2023-08-10 00:52 UTC, merged

2023-08-10 00:52 UTC, zwliew commented
Thank you!