Grey Out Deprecated Courses In PreReq Tree
nusmodifications/nusmods pull request #3647
Opened 2023-12-25 13:22 UTC by EssWhyy

## Context

Implements #3473 

## Implementation

Connects ModuleTree.tsx to the Redux Store, and uses the getModuleCondensed() function to check if the module code in each node points to a valid module in the current module bank. If the module has been deprecated, we remove the hoverable color-${layer} classname tag from the module node. The node will be greyed out and no longer appear hoverable as shown below

UI Example:

![deprecated courses](https://github.com/nusmodifications/nusmods/assets/39799639/997e9d69-09c5-4425-89db-ceb907c37c67)

## Other Information

2024-01-30 04:19 UTC, ravern requested changes
Thanks for the PR!

I have one nitpick on the conditional rendering code, but overall LGTM!

2024-01-30 04:19 UTC, ravern commented on website/src/views/modules/ModuleTree.tsx
> +  }
Instead of repeating the rendering code below, is it possible to leverage conditional classes via `classnames` to achieve the same behaviour? For e.g.

```typescript
return (
    <div
      className={classnames(styles.node, styles.moduleNode, {
        [`hoverable color-${layer}`]: !!moduleActive,
        [styles.prereqNode]: isPrereq,
      })}
    >
      {prefix && <span className={styles.prefix}>{prefix}</span>}
      <LinkModuleCodes className={styles.link}>{name}</LinkModuleCodes>
    </div>
  );
```

2024-02-03 09:48 UTC, EssWhyy commented on website/src/views/modules/ModuleTree.tsx
> +  }
Ah ok, I was wondering if there was a way to avoid repeating the code, this seems to work fine, thanks!

2024-03-04 03:17 UTC, kokrui approved these changes
LGTM (and ravern!), merging now

2024-03-04 09:42 UTC, merged

2024-03-11 10:47 UTC, yimqiy commented
Ooh just saw this :) thanks for implementing!

Just a note - pre-reqs that are not individual courses to begin with are also greyed out, like the one below:
![image](https://github.com/nusmodifications/nusmods/assets/40708187/8270d809-162e-48f4-a876-26708f169f4b)

2024-03-19 01:12 UTC, kokrui commented
@yimqiy thanks for the comment! I do think it makes sense to have different behaviour (i.e. don't just grey them out) for these pre-req tree nodes -- let's track this as an issue