Fix for Mobile Google Calendar Odd/Even Week Imports
nusmodifications/nusmods pull request #3684
Opened 2024-03-24 15:03 UTC by onx001

Added interval checking for numeric week calculations as Google Calendar imports on mobile do not handle exclusions well.

Also fixed additional tutorials for odd/even weeks being added after Week 11/13.

## Context
#3679 
.ics iCal exports have weird handling issues with even/odd weeks, namely extra lessons after the intended one and a lack of proper exclusion handling for mobile Google Calendar users.

## Implementation
A simple interval calculator is implemented for the calculateNumericWeek function, and the count and interval fields are passed to the ics generator where previously they were missing and filled through exclusions.

## Other Information
Current handling of edge case intervals that do not follow the regular pattern or that skip intervals might still have the bug for extra lessons. Needs further investigation.

2024-03-25 06:01 UTC, kokrui commented on website/package.json
> +    "jest-environment-jsdom": "^29.7.0",
Thanks for the PR! I'll get to reviewing and testing the code by this Wednesday. In the meantime, can I check if bumping the dependencies here (and creating a package.json for the monorepo) is required for the change to work? Otherwise, could you help remove those diffs (`package.json`, `website/package.json`, and `website/src/utils/yarn.lock` from this PR? Thanks!

2024-03-25 08:39 UTC, onx001 commented on website/package.json
> +    "jest-environment-jsdom": "^29.7.0",
Alright, done! The dependencies were not required to be updated. I have not worked with yarn before so was a little unfamiliar with the process. Thank you for your help!

2024-03-27 08:45 UTC, kokrui approved these changes
LGTM

2024-03-27 08:58 UTC, kokrui requested changes
Hold on, my bad -- it looks like this new PR is creating events beyond the end date of the semester. @onx001 if you look export from this PR's deployment (https://nusmods-website-zrekiv0gl-mods-bot.vercel.app/timetable/sem-1) does the calendar work for you?

2024-04-17 07:40 UTC, ravern commented
Hi, just tested out this PR as well, and there seems to be another bug: events on odd weeks only show up _before_ recess week, while events on event weeks only show up _after_ recess week.

Here's the timetable I used and I've also attached the exact .ics file I used.

https://nusmods-website-zrekiv0gl-mods-bot.vercel.app/timetable/sem-2/share?ME2115=LAB:2G1,TUT:2G,LEC:1&ME2121=LAB:2G3,TUT:2N,LEC:1

[nusmods_calendar.ics.zip](https://github.com/nusmodifications/nusmods/files/15007587/nusmods_calendar.ics.zip)

2026-05-23 04:21 UTC, ravern commented
Hey, we're doing some clean ups over the summer. Closing this for now because this PR is stale. Feel free to re-open this if you think otherwise!

2026-05-23 04:21 UTC, closed without merging