Release Planner
nusmodifications/nusmods pull request #3696
Opened 2024-03-27 17:03 UTC by wr1159

## Context

Resolves #3689 

## Implementation

* Display planner in Navbar on all devices (Including mobile devices which didn't show the planner in the past, was it intended or was it a bug?)
* Remove `currentTests` in `BetaToggle`
* Remove beta feedback for Planner page

| Description | Before | After |
|-------|--------|--------|
| No more beta toggle| <img width="970" alt="image" src="https://github.com/nusmodifications/nusmods/assets/56021409/e4814490-aa9f-4730-9db0-37e9565d9003">| <img width="962" alt="image" src="https://github.com/nusmodifications/nusmods/assets/56021409/56d48eb2-c03c-4552-98e5-6cf882856489"> |
|Planner tab in mobile navbar| <img width="571" alt="image" src="https://github.com/nusmodifications/nusmods/assets/56021409/15d6a9bc-d1d3-4f6b-878c-1282371dd808"> | <img width="574" alt="image" src="https://github.com/nusmodifications/nusmods/assets/56021409/efb783df-07e7-44e1-b8bb-2411fe5d1954"> |
| No more leave feedback button| <img width="731" alt="image" src="https://github.com/nusmodifications/nusmods/assets/56021409/01d90787-dcd4-4853-bdb6-92573062bb40"> | <img width="987" alt="image" src="https://github.com/nusmodifications/nusmods/assets/56021409/2a401269-c3f5-48d3-b655-93ec26714231">| 

## Other Information

Since there's no more test, the beta test toggle in settings doesn't appear by default anymore. Is this intended?

2024-03-30 15:28 UTC, kokrui reviewed
Thanks for the PR (including the screenshots and all)!

I think this PR looks good to me and I approve of it in-principle, but I agree with you that we should fix the mobile UI first before merging this. Thanks for pointing that out!

2024-04-01 14:16 UTC, kokrui commented
I'll approve this pending merge conflicts and stuff, but merging will be on hold for now due to some internal requirements with NUS. We expect to be able to merge in around a month or so 🙏

2024-07-30 13:33 UTC, zwliew requested changes

2024-07-30 13:33 UTC, zwliew commented on website/src/views/planner/PlannerContainer/PlannerContainer.scss
> +      margin: auto;
Can we remove these style changes? They make the layout look worse on small form factors.

2024-07-30 13:34 UTC, zwliew approved these changes

2024-07-30 13:49 UTC, merged

2024-07-30 13:49 UTC, zwliew commented
LGTM, thanks!