Fix/planner scroll
nusmodifications/nusmods pull request #3701
Opened 2024-03-31 14:30 UTC by jloh02

## Context
Fix #3698 with additional fixes to ensure header remains in size

## Implementation
- CSS fixes for overflows including scrollable and `no-wrap`
- Set minimum width for trash button
- `useMediaQuery` to allow settings button to reduce to an icon button

2024-04-01 03:49 UTC, kokrui requested changes
Thanks for the PR! It's really well-written and there are a lot of thoughtful decisions being made here, great work!

I'm happy with the feature and functionality, just a few small style and consistency nits before we get this merged

2024-04-01 03:49 UTC, kokrui commented on website/src/views/planner/PlannerButton.tsx
> +export default function PlannerButton(props: Props) {
I think I'd prefer if this file / component was called something like `PlannerSettingsButton`, since there are a few buttons on this page

2024-04-01 03:49 UTC, kokrui commented on website/src/views/planner/PlannerButton.tsx
> +export default function PlannerButton(props: Props) {
also, even though this is a simple component (and we don't use the `children`) prop, I believe in this repo we lean towards writing React components as functional component with destructured props, so let's do that here

i.e.

```js
const PlannerButton: React.FC<Props> = ({
  onClick
}) => {

// (then props.onClick -> onClick)
```

and then `export default PlannerButton;` at the bottom

2024-04-01 03:49 UTC, kokrui commented on website/src/views/planner/PlannerContainer/PlannerContainer.scss
> +  color: theme-color("danger");
I have no current opinion on this, and I'm sure we'd be happy to consider/accept a different PR where we migrate all colours names from single-quotes to double-quotes, but for now it looks like the repo uses single-quotes for colour names like this and I'd prefer consistency

2024-04-01 03:49 UTC, kokrui commented on website/src/views/planner/PlannerContainer/PlannerContainer.scss
> +@import "~styles/utils/modules-entry";
similar to below, right now it seems the repo uses single-quotes for import paths, so I'd prefer that here

2024-04-01 06:23 UTC, merged

2024-04-03 05:25 UTC, ZhangYiJiang commented on website/src/views/planner/PlannerContainer/PlannerContainer.scss
> +    width: 100%;
I'm confused by this - it seems this just makes the right side items take up a lot of space while squashing the heading and "Send feedback" button 


https://github.com/nusmodifications/nusmods/assets/445650/8adef033-8bc4-4ac5-9765-2f1d261a8678

2024-04-03 05:25 UTC, ZhangYiJiang commented on website/src/views/planner/PlannerContainer/PlannerContainer.scss
>      margin: 0;
This should be moved back to under h1 - the div does not intrinsically have margin so this won't do anything here, and having margin: 0 on the h1 overrides the default so the h1 is correctly positioned vertically 


https://github.com/nusmodifications/nusmods/assets/445650/ff05249f-992c-4c54-9b34-2b44678d34b8

2024-04-03 05:25 UTC, ZhangYiJiang commented on website/src/views/planner/PlannerSettingsButton.tsx
> +      {narrowViewport ? '' : 'Settings'}
This should wrap the text in `sr-only` utility class instead of removing it so that this text is still available to screen readers https://getbootstrap.com/docs/4.6/utilities/screen-readers/ (there's a number of places in the app where we use `display: none` to do this which is unfortunately has the same issue). 

If we just want to change the layout on mobile, prefer CSS media queries instead

2024-04-03 05:55 UTC, jloh02 commented on website/src/views/planner/PlannerContainer/PlannerContainer.scss
> +    width: 100%;
Rectified in #3704