Add close button in planner settings modal
nusmodifications/nusmods pull request #3702
Opened 2024-04-01 08:31 UTC by jloh02

## Context
Fix #3699 

## Implementation
- Use existing `CloseButton` component
- Changes the container to flexbox so that 0 height item still maintains the `margin-bottom`

2024-04-01 09:30 UTC, kokrui requested changes
Thanks for the PR again! Just a tiny bit of dead code to shave off before I LGTM and merge

2024-04-01 09:30 UTC, kokrui commented on website/src/views/planner/PlannerSettings.scss
Looks like this CSS selector matches on nothing, since there doesn't exist any `section` element that is the first child of its parent. With the addition of the close button diff, the first section element is now the second child of the settings div. We can remove this dead code!

2024-04-01 09:48 UTC, jloh02 commented on website/src/views/planner/PlannerSettings.scss
Oops sorry about that. Forgot to remove it after moving the CloseButton out of a section

2024-04-01 10:22 UTC, kokrui approved these changes
LGTM!

2024-04-01 10:22 UTC, merged

2024-04-04 00:36 UTC, ZhangYiJiang commented
The approach is not wrong, but this means that the close button always takes up a row on its own. The close button already has styles so it is on the right side of the modal (using floats). You can also adjust the positioning after that using negative margin top and right. 


https://github.com/nusmodifications/nusmods/assets/445650/7f502ed4-c27c-4940-b4f2-667d7a8368cd