Add new Button on Course Page to Add Course to Planner
nusmodifications/nusmods pull request #3731
Opened 2024-05-31 08:56 UTC by EssWhyy

## Context

Implementation for #3399 

## Implementation

Added a button to each module page to allow a user to save the module to the planner in the Plan to Take section, acting like a save button of sorts. 

If it is already added to Plan To Take, the button will remove the module from there instead. 

Test Run:

https://github.com/nusmodifications/nusmods/assets/39799639/bb7ccd98-f413-4400-9ca1-12440988319b

## Other Information

2024-06-30 14:32 UTC, ravern requested changes
Have verified that this works! Thanks for your contribution.

The code looks good, full props (pun intended) for following the current style of the surrounding components.

_This is completely optional_, but it would be a nice-to-have if we could create new components in the functional style instead of class style — I would like to slowly move the codebase towards this pattern.

The specific code comments are just nits, and I would still merge them in if you don't touch the code referenced in those comments.

I'm requesting changes only because of the **component name**, which I believe could be more specific than `SaveModuleButton`. Something that references the planner / plan-to-take action might be better.

2024-06-30 14:32 UTC, ravern commented on website/src/views/components/module-info/SaveModuleButton.tsx
> +  }
Is it possible to use a `.some` call here instead?

e.g. `planToTakeModules.some(m => m.moduleCode === module.moduleCode)`

2024-06-30 14:32 UTC, ravern commented on website/src/views/components/module-info/SaveModuleButton.tsx
> +  }
Is it possible to use a `.find` call here instead?

e.g. `planToTakeModules.find(m => m.moduleCode === module.moduleCode)?.id ?? '0'`

2024-06-30 14:32 UTC, ravern commented on website/src/views/components/module-info/SaveModuleButton.tsx
> +    const PLAN_TO_TAKE_SEMESTER = -2;
Is it possible for us to import these constants from `src/utils/planner.ts' instead?

Or better yet, create a new function that more accurately represents what this code is trying to do, i.e., add a module so far into the future that it will definitely be in the "plan to take" section (correct me if this _not_ what the code is trying to do)?

2024-06-30 14:32 UTC, ravern commented on website/src/views/components/module-info/SaveModuleButton.scss
> +}
Seems to be unused?

2024-06-30 14:32 UTC, ravern commented on website/src/views/components/module-info/SaveModuleButton.scss
> +  }
Global seems like quite a large scope, do you know if this styling is actually applied on the button?

2024-12-02 10:32 UTC, zwliew requested changes

2024-12-02 10:32 UTC, zwliew commented on website/src/views/components/module-info/SaveModuleButton.tsx
> +    if (loading != null && isModuleInPlanToTake(module, planToTakeModules)) {
`loading ` doesn't seem used. I don't think a loading indicator is necessary so I think we can remove it entirely.

2024-12-02 10:32 UTC, zwliew commented on website/src/views/components/module-info/SaveModuleButton.tsx
> +  }
This is simple enough to be inlined into the `render()` function.

2024-12-02 10:32 UTC, zwliew commented on website/src/views/components/module-info/SaveModuleButton.tsx
> +      });
To add onto Ravern's comment [above](https://github.com/nusmodifications/nusmods/pull/3731/files#r1660190895) , the right thing to do is probably to add the following function definition to `actions/planner.ts`:

```js
export function addPlanToTakeModule(moduleCode: ModuleCode) {
// call addPlannerModule here with some defaults
}
```

2024-12-02 10:32 UTC, zwliew commented on website/src/views/components/module-info/SaveModuleButton.tsx
> +  onSelect(semester: Semester) {
Similar to `loading`, we don't actually use `semester`, so we can remove it.

2024-12-02 10:32 UTC, zwliew commented on website/src/views/components/module-info/SaveModuleButton.tsx
> +  }
Going even further, I reckon we can replace `isModuleInPlanToTake` and `getModuleId` with:

```js
function findModule(
  module: Module,
  planToTakeModules: PlannerModuleInfo[],
): PlannerModuleInfo | undefined {
// use planToTakeModules.find(...)
```

and adjust the rest of the calling code accordingly.

2024-12-02 10:32 UTC, zwliew commented on website/src/views/modules/ModulePageContent.tsx
> +                  </div>
Please merge this into the block above (lines 251 to 253)

2024-12-16 10:34 UTC, merged

2024-12-16 10:34 UTC, zwliew commented
I went ahead and made the requested clean up changes. Thanks for your contribution!