Add duplicate modules conflict
nusmodifications/nusmods pull request #3738
Opened 2024-07-04 04:03 UTC by ChillinRage

Duplicate conflict checks if there are modules with the same module code added to the same academic year and semester.

## Context

Proposal to fix #3732 which having same modules in the same year/semester shows no warnings.

## Implementation

Added a new conflict that checks if the module list for a given semester has more than one module of the same module code.

## Other Information

Added test case for the conflict, though I'm slightly confused as to what's the role/difference between `planner` and `moduleBank` (the variables in the `planner.test.ts`)?

2024-07-14 17:17 UTC, ravern requested changes
Thanks for this contribution! Been a bit busy, sorry for getting to this only now.

Awesome that you've added new tests for this, and I like the solution that you've come up with by adding a new conflict type!

I'm requesting changes because it would be great to have an error message indicating why this conflict occured. As can be seen in the screenshot, for pre-req conflicts there is a really specific reason, whereas for duplicate conflict the message is blank.

<img width="200" alt="image" src="https://github.com/user-attachments/assets/fa56a141-07b8-4f4b-aacc-35571194fbbb">

To render the error message, you can check out `website/src/views/planner/PlannerModule.tsx`.

2024-07-14 17:17 UTC, ravern commented on website/src/types/planner.ts
> +};
nit: `Duplicate` -> `DuplicateConflict`

2024-07-16 15:10 UTC, ChillinRage commented
Apologies for the missing message and late response too. I've added the section that should display a warning message. Is there a way in which I can run a live webpage that allows me to test my local changes?

2024-07-16 17:00 UTC, ravern commented
> Apologies for the missing message and late response too. I've added the section that should display a warning message. Is there a way in which I can run a live webpage that allows me to test my local changes?

Yes! Once you've cloned the repository, just run `cd website` to enter the website folder, `yarn install` to install all the dependencies, and then `yarn start` to start the web server.

Let me know if that works.

2024-07-17 14:08 UTC, ChillinRage commented
Yes I just tried `yarn start` and it works. Thank you!

As for the conflict message, it does appear after the changes.
![image](https://github.com/user-attachments/assets/e5653715-c9ad-4e59-a29f-d4255bda284d)

2024-07-17 16:59 UTC, ravern approved these changes
LGTM

2024-07-17 17:06 UTC, merged