Fixed double clicking issue on touch devices
nusmodifications/nusmods pull request #3750
Opened 2024-07-18 07:43 UTC by Incogdino

## Context
 #3205 

## Implementation
 

![image](https://github.com/user-attachments/assets/2543039c-3f81-46ad-a079-a004c7da6c42)
Changed touch prop to trigger as "hold" if the button is held for more than 300ms, else it will be interpreted as a click and onClick() function is called instead. This only affects touch devices.

https://github.com/user-attachments/assets/e7ac8ce2-768e-41ae-a117-9358b27ea5c6

Running yarn test was successful. 
## Other Information

This is my first time contributing to nusmods. Pardon me if there are any mistakes :)

2024-07-20 15:27 UTC, zwliew commented
Hi, thanks for contributing! However, I don't understand what the issue is here. I get the right behaviour on Android: merely tapping a button clicks it, but holding for a few milliseconds doesn't click it and instead displays the tooltip. Of course, maybe there is an issue on other device/OS/browser combinations. May I know what issue you're facing and on what device+browser+OS?

2024-07-20 15:31 UTC, Incogdino commented
> Hi, thanks for contributing! However, I don't understand what the issue is here. I get the right behaviour on Android: merely tapping a button clicks it, but holding for a few milliseconds doesn't click it and instead displays the tooltip.
> 
> Of course, maybe there is an issue on other device/OS/browser combinations. May I know what issue you're facing and on what device+browser+OS?

2024-07-20 15:39 UTC, Incogdino commented
Hello sorry clicked on the wrong button 😓

https://github.com/user-attachments/assets/019a392c-e099-4798-aa1b-73426f4cf47c

Here is what I got when I tried in the video and the result : 
1. Single click on hide -> Button turns grey with no effect
2. Single click on delete -> Button turns grey with no effect
3. Hold delete button -> Tooltip pops up 
4. Click outside of the button -> Button loses grey color 
5. double click on delete button -> Module gets removed 
6. Click on undo button -> Module gets added back 

Device: ios safari

**Expected reaction** 
onClick function should trigger on a single click for both delete and hide

2024-07-22 07:48 UTC, zwliew requested changes
I see. It mostly looks good to me, except for some minor issues.

2024-07-22 07:48 UTC, zwliew commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Please remove this file. I believe this was mistakenly generated by running `yarn` in the root directory instead of the `website` directory.

2024-07-22 07:48 UTC, zwliew commented on website/src/views/timetable/TimetableModulesTable.tsx
> +          <Tooltip content={removeBtnLabel} touch={['hold', 300]}>
A 300ms delay is quite noticeable. Can we change it to something more shorter, say 50ms?

2024-07-22 07:48 UTC, zwliew commented on website/src/views/timetable/TimetableModulesTable.tsx
> +          <Tooltip content={hideBtnLabel} touch={['hold', 300]}>
Same thing here.

2024-07-22 08:12 UTC, Incogdino commented on website/src/views/timetable/TimetableModulesTable.tsx
> +          <Tooltip content={removeBtnLabel} touch={['hold', 300]}>
Got ya :) I've made the necessary changes

2024-07-22 08:43 UTC, zwliew approved these changes

2024-07-22 08:43 UTC, merged

2024-07-22 08:43 UTC, zwliew commented
Thanks!