replaced occurences of google groups email
nusmodifications/nusmods pull request #3795
Opened 2024-08-21 06:57 UTC by kaze-droid

## Context
Issue #3777 
Renamed all occurences of `nusmods<at>googlegroups<dot>com` to `mods<at>nusmods<dot>com`

2024-08-21 07:24 UTC, kokrui requested changes
Mostly LGTM except for the comment below! Make sure you generalize the feedback to other instances where you changed googlegroups -> mods@nusmods

2024-08-21 07:24 UTC, kokrui commented on README.md
> +- Email: mods@nusmods.com (for security related issues please email mods@nusmods.com instead)
This doesn't look right -- now that the default email is `mods@nusmods.com`, there's no need to specify that you should use that email for security-related issues too

2024-08-21 07:40 UTC, kaze-droid commented on README.md
> +- Email: mods@nusmods.com (for security related issues please email mods@nusmods.com instead)
fixed by removing the back portion in brackets

2024-08-27 07:34 UTC, zwliew approved these changes

2024-08-27 07:35 UTC, merged

2024-08-27 07:35 UTC, zwliew commented
Thank you!