Fix: Use local venue data for development instead of prod data
nusmodifications/nusmods pull request #3810
Opened 2024-08-24 01:31 UTC by kavishsathia

## Context

Closes #3803 

## Implementation

The solution checks if the user is on localhost, and if they are, it will opt to use the local venue data instead of the production data by default. To override this behavior, the user can add a query parameter `prodVenue` to their URL, which will enable them to use production data instead.

## Other Information

2024-09-10 01:28 UTC, zwliew commented
May I know what's the motivation behind changing this default?

2024-09-12 04:08 UTC, ravern approved these changes
Thank you for this contribution! Sorry it took me this long to get to it.

I like the idea of flipping the venue fetching such that it uses local by default and global in production.

Was there a specific reason you used a `window.location.hostname` check instead of the current environment string? If there wasn't, I'm thinking it might be better to use the existing config than the use the hostname.

2024-09-12 04:08 UTC, ravern commented on website/src/utils/debug.ts
> +
Would it be make sense to use `NUSMODS_ENV` instead?

```typescript
// Snippet from src/types/global.d.ts

/**
 * NUSMods deployment environment.
 *
 * **Note:** although these environments may share the same name as
 * `NODE_ENV` and other envs, there are subtle differences. Definitions:
 *
 * - `production`: a production deployment of NUSMods, i.e. a deployment meant to
 *   be used by the general public.
 * - `staging`: a deployment of NUSMods's main development branch, which is
 *   not meant to be used by the general public but which may be promoted to
 *   production at any point.
 * - `preview`: a deployment of work-in-progress branches, e.g. PR deploy
 *   previews.
 * - `test`: we are in a test environment, e.g. a jest test run.
 * - `development`: all other situations.
 */
declare const NUSMODS_ENV: 'development' | 'production' | 'staging' | 'preview' | 'test';
```

2024-09-12 04:08 UTC, ravern commented on website/src/utils/debug.ts
> +  if (process.env.JEST_WORKER_ID !== undefined) return false;
Using `NUSMODS_ENV` would allow checking for `NUSMODS_ENV === 'test'` as well.

2024-09-12 04:08 UTC, ravern requested changes
Sorry, meant to request changes.

2024-11-25 07:00 UTC, zwliew approved these changes

2024-11-25 07:00 UTC, zwliew commented
I've made the following changes:
- Use NUSMODS_ENV to detect test and development environments
- Use localVenue and prodVenue flags to override the defaults in each case.

2024-11-25 07:00 UTC, merged