weeks of classes checking on today dashboard
nusmodifications/nusmods pull request #3814
Opened 2024-08-28 08:23 UTC by xinyuwang-nus

## Context

https://github.com/nusmodifications/nusmods/issues/3757
## Implementation

## Other Information

2024-09-30 13:10 UTC, ravern requested changes
Sorry for the delay in reviewing this!

I've added https://github.com/nusmodifications/nusmods/issues/3757#issuecomment-2383138799 after doing a deep dive into the issue.

I'm good to merge this once the linting errors are fixed, since this solves the issue for now. You can find the linting errors by clicking the "Details" link in the failing "build_and_test" workflow, then navigating to the "Tests" tab.

Here's a direct link to that page: https://app.circleci.com/pipelines/github/nusmodifications/nusmods/14863/workflows/fc3ce863-17e5-49a2-84e9-2d99e12ab411/jobs/89894/tests

2024-10-15 19:19 UTC, xinyuwang-nus commented
> Sorry for the delay in reviewing this!
> 
> I've added [#3757 (comment)](https://github.com/nusmodifications/nusmods/issues/3757#issuecomment-2383138799) after doing a deep dive into the issue.
> 
> I'm good to merge this once the linting errors are fixed, since this solves the issue for now. You can find the linting errors by clicking the "Details" link in the failing "build_and_test" workflow, then navigating to the "Tests" tab.
> 
> Here's a direct link to that page: https://app.circleci.com/pipelines/github/nusmodifications/nusmods/14863/workflows/fc3ce863-17e5-49a2-84e9-2d99e12ab411/jobs/89894/tests

2024-10-16 06:30 UTC, ravern commented on website/src/views/today/TodayContainer/TodayContainer.tsx
Looks good, and thank you for adding these comprehensive tests! I think the inconsistencies are small and can be fixed in a follow-up PR, I'm more interested in merging this one which fixes the bigger bug.

2024-10-16 06:31 UTC, xinyuwang-nus commented on website/src/views/today/TodayContainer/TodayContainer.tsx
sounds good

2024-10-16 06:31 UTC, ravern approved these changes
LGTM, thank you for addressing this issue! Definitely not a trivial one to solve.

2024-10-16 06:39 UTC, merged