fixed privacy opt-out button not clickable issue
nusmodifications/nusmods pull request #3818
Opened 2024-09-04 08:11 UTC by yk-tuturu

## Context
closes #3254 

## Implementation
 following instructions detailed in issue #3254, implemented checks to see if matomo is initialized and disables the privacy toggle if blocked by an ad-blocker

## Other Information

2024-09-18 06:56 UTC, ravern reviewed
Thank you for your contribution! I am able to see your fix as intended — the toggle is set to "Opt-out" and disabled if `matomo` is not initialised.

While I think your solution fulfils the [original comment](https://github.com/nusmodifications/nusmods/issues/3254#issuecomment-868986124) made by an earlier maintainer, I think that adding a hook is unnecessary (and an incorrect usage of React hooks, see [this comment](https://github.com/nusmodifications/nusmods/pull/3818#discussion_r1764511588)).

I think the crux of this issue is if `matomo` is `undefined`, the opt-out toggle cannot be clicked, leading the user to believe that they cannot opt-out of the tracking, when in fact there is no tracking at all.

The current code that modifies the UI component actually already fixes this issue, and the addition of the hook is unnecessary. I think if **we reverse the changes to the hook portion of this PR**, it will LGTM.

2024-09-18 07:04 UTC, ravern commented on website/src/bootstrapping/matomo.ts
> +}
In the following code:
```typescript
useEffect(() => {
    setMatomoCopy(matomo);
  }, [matomo]);
```
This effect is only ever called once (on component mount) since the `matomo` variable exists outside of the React context. This is reflected by the linter as well: 

```
React Hook useEffect has an unnecessary dependency: 'matomo'. Either exclude it or remove the
dependency array. Outer scope values like 'matomo' aren't valid dependencies because mutating
them doesn't re-render the component.
```

2024-09-18 07:06 UTC, ravern requested changes
Remove hook

2025-07-10 20:06 UTC, ZhangYiJiang commented on website/src/bootstrapping/matomo.ts
> +}
I don't really understand this code at all. This in effect is forcing a re-render, but there are better ways to do that if that's the intention

2026-05-23 04:09 UTC, ravern commented
Hey, we're doing some clean ups over the summer. Closing this for now because both the issue and the PR are stale. Feel free to re-open this if you think otherwise!

2026-05-23 04:09 UTC, closed without merging