Add TA mode
nusmodifications/nusmods pull request #3875
Opened 2024-12-01 09:45 UTC by leslieyip02

## Context

Closes #3804.

Adds an option for TAs to hide non-TA lessons. The original issue requested an option to hide non-tutorial lessons, but this would hide labs and recitations as well, so I decided to implement a dropdown menu to toggle TA mode for different lesson types.

I have not been a TA before, so do let me know if this makes sense?

## Implementation

- Each module has a few different lesson types, so `TimetableState` was updated to have a `TaModuleConfig`, which maps each module to an array of lesson types.
- For modules with TA lessons, `TimetableContent` only renders lessons which are marked as TA and ignores other lesson types.
- TA modules will not be counted towards total units, and will also not be shown in the exam calendar.
- TA modules are suffixed with `(TA)` in the timetable
- The `ColorPicker` for TA modules has a half-filled color box

### Toggle TA mode

https://github.com/user-attachments/assets/7c8e890e-802d-44fa-bea6-77fd7e713ece

### No TA-able mods

When the mod has no TA-able mods (i.e. just lectures), the menu button is disabled.

![image](https://github.com/user-attachments/assets/1852b4ca-c2a6-482b-b402-ff92320f26c5)

### Export/Import

https://github.com/user-attachments/assets/965b2bf2-6415-4a59-a2fa-5b6d1ef6a0ca

### Exam clash

TA mods are not shown in the exam calendar, and do not contribute to exam clashes.

Left: Updated, Right: Current

![Screenshot 2024-12-01 165844](https://github.com/user-attachments/assets/8c99b1b2-5c6b-4492-8c5c-b0968d6e1b12)

I also made it so that hidden mods no longer creates a clash warning.

![Screenshot 2024-12-01 165811](https://github.com/user-attachments/assets/76da888b-385f-4721-96c9-8db9e6278e1f)

## Other Information

I had some trouble trying to get `Tooltip` to work with `Downshift`. When using `Tooltip` inside `DownShift`, I needed to call `getRootProps`, but it seems to be creating these warnings from `tippy.js`:

![Screenshot 2024-12-01 170802](https://github.com/user-attachments/assets/9b5d6d09-ff79-4a88-8832-c43349cc9034)

Since the versions of both `@tippy.js/react` and `downshift` are quite outdated, I wasn't able to find docs to resolve the warnings.

2024-12-17 09:12 UTC, zwliew commented
This looks quite good so far! However, the ability to add multiple tutorials/lab/recitations to the timetable in TA mode is missing. I suggest making each tutorial/lab/recitation slot toggleable in TA mode, instead of the usual behaviour that switches between slots.

2024-12-17 09:12 UTC, zwliew requested changes
This looks quite good so far! Thanks for even considering timetable exports and adding some tests.

However, the ability to add multiple tutorials/lab/recitations slots to the timetable in TA mode is missing. This is useful for those TA-ing multiple slots. I suggest making each tutorial/lab/recitation slot toggleable in TA mode, instead of the usual behaviour that switches between slots.

2024-12-23 16:45 UTC, leslieyip02 commented
I've added the ability to add multiple slots in TA mode. Let me know if the implementation makes sense.

https://github.com/user-attachments/assets/2495cedd-4cf6-43dc-a3ee-4f3b83e3de74

2024-12-27 05:25 UTC, zwliew requested changes
The implementation looks mostly fine! The only main issue is that there should be a single TA mode toggle for each course instead of per-lesson-type toggles. Besides that, there are a few minor questions and bugs to be resolved.
This PR should be ready for merging soon after these issues are resolved.

2024-12-27 05:25 UTC, zwliew commented on website/src/views/timetable/ModulesTableFooter.tsx
> +}
Refactoring this code into two other functions is quite unnecessary IMO, since the variables `totalMCs` and `shownMCs` already tell what the code is trying to do.

2024-12-27 05:25 UTC, zwliew commented on website/src/views/components/ColorPicker.scss
> +    border-style: dashed !important;
Is `!important` necessary here?

2024-12-27 05:25 UTC, zwliew commented on website/src/types/timetables.ts
> +  [moduleCode: ModuleCode]: TaLessonConfig;
It would be simpler to map `ModuleCode` to an array of pairs`(lessonType, ClassNo)[]`. Do we need the extra indirection from the `TaLessonConfig` here?

2024-12-27 05:25 UTC, zwliew commented on website/src/utils/ical.ts
> +        }
I don't think this works correctly. The guard should simply return early if `moduleCode in taModules`, and we should have a separate loop afterwards to go through `taModules` and add them to the calendar.

2024-12-27 15:57 UTC, leslieyip02 commented on website/src/views/components/ColorPicker.scss
> +    border-style: dashed !important;
I marked it with `!important` to handle the case where the mod is tagged as hidden and TA. But actually, I can just rearrange the styles for `&.ta` to be above `&.hidden` so that the dashed border will still show

2024-12-27 16:04 UTC, leslieyip02 commented on website/src/views/timetable/ModulesTableFooter.tsx
> +}
I initially created the functions so that it would be easier to write unit tests, but you are right that it's a bit redundant.

2024-12-28 01:59 UTC, zwliew commented on website/src/views/timetable/ModulesTableFooter.tsx
> +}
Oh good point -- I didn't notice the tests.

2024-12-29 12:58 UTC, leslieyip02 reviewed
To test `export`, I had to change some configurations. I am not too sure if the changes are appropriate, but I couldn't get the `export` to work without the changes. Let me know if I missed anything?

2024-12-29 12:58 UTC, leslieyip02 commented on export/src/render.ts
> +    args: ['--disable-gpu'],
I'm not sure if this is absolutely necessary, but I couldn't get `browser.newPage()` to work without this.

2024-12-29 12:58 UTC, leslieyip02 commented on docker-compose.yml
> +      - PAGE=http://website:8081/timetable-only/
I'm not sure if this is necessary.

2024-12-29 13:04 UTC, leslieyip02 commented
The TA mode toggle is applied on a per-module basis now:

![](https://github.com/user-attachments/assets/1b3da4e3-7ec0-484c-8bc4-afa00f1f4037)

2025-01-02 06:10 UTC, zwliew requested changes

2025-01-02 06:57 UTC, zwliew commented on export/src/render.ts
> +    args: ['--disable-gpu'],
I think this is fine.

2025-01-02 07:00 UTC, zwliew commented on docker-compose.yml
> +      - PAGE=http://website:8081/timetable-only/
We should make the same change for `docker-compose.prod.yml`.

2025-01-02 07:02 UTC, zwliew commented on docker-compose.yml
> +      - PAGE=http://website:8081/timetable-only/
We should make the same change for `docker-compose.prod.yml`

2025-01-02 07:08 UTC, zwliew commented on export/src/types.ts
> +  };
Should these be `hidden` and `ta` instead?
Also, it might be worth copy pasting the necessary type definitions (i.e. `TaModulesConfig`, `ModuleCode`) from `website/src/types` instead.

2025-01-02 13:30 UTC, leslieyip02 commented on website/src/views/timetable/TimetableContent.tsx
> +  );
For reference, `hydrateSemTimetableWithAllLessons` is used here.

2025-01-02 15:00 UTC, zwliew commented on website/src/utils/timetables.ts
> +    ...hydrateSemTimetableWithTaLessons(taModules, modules, semester),
Indeed. What I meant was that we should not mess with  the implementation of `hydrateSemTimetableWithLessons` in this PR -- the goal is to keep the PR concise and to keep the logic for hidden and TA-ed courses consistent.

How about this:
- Keep the original implementation of `hydrateSemTimetableWithLessons`. That is, the resulting `SemTimetableConfigWithLessons` should keep all lessons, even those for hidden and TA-ed courses.
- In places where we want to filter out lessons that the user doesn't TA for (i.e. image/PDF exports, Today page, timetable import), add some additional logic to filter them out at the call sites. This should be somewhat similar to following changes done for hidden courses:

Today page: https://github.com/nusmodifications/nusmods/pull/3927
Image/PDF exports: https://github.com/nusmodifications/nusmods/pull/3925

As for timetable imports, you'd need to slightly modify https://github.com/nusmodifications/nusmods/pull/3875/files#diff-0da48c065607eeaa76534e07e1141c7cda4f7da06d03b7fc69bee4dfd355840aR536-R543

2025-01-02 15:24 UTC, leslieyip02 commented on website/src/utils/timetables.ts
> +    ...hydrateSemTimetableWithTaLessons(taModules, modules, semester),
Ah ok, that makes sense.

2025-01-03 08:39 UTC, zwliew approved these changes
I merged in master and cleaned up the code slightly, but overall LGTM. Great job on this!

2025-01-03 08:58 UTC, merged

2025-01-03 10:04 UTC, HollaG commented
Just want to piggyback on this thread - it appears certain courses cannot be set to TA mode (example: CS2103T, CS3281). Should I file a bug report?

2025-01-03 10:07 UTC, zwliew commented
> Just want to piggyback on this thread - it appears certain courses cannot be set to TA mode (example: CS2103T, CS3281). Should I file a bug report?

Good catch - please go ahead and file one.

2025-01-03 10:18 UTC, HollaG commented
I really would like this feature to become useful to TAs, but the implementation of removing only the lectures is also a little bit restrictive, unfortunately - most CS courses that have lab + tutorials often also have separate TAs for them, and the current implementation doesn't allow hiding of either lab/tut individually. 

Nevertheless, thank you guys for your efforts!